import { useState } from "react";
import { api } from "./BridgeApi.js";
import { Icon } from "./Icons.jsx";
import { Alert, Badge, dateTime, Empty, number, PlatformBadge, useProjectResource } from "./ui.jsx";

const metrics = ["engagement", "views", "impressions", "likes", "comments", "shares", "saves", "clicks"];
const labels = { engagement: "Engagement", views: "Views", impressions: "Impressions", likes: "Likes", comments: "Comments", shares: "Shares", saves: "Saves", clicks: "Clicks" };
const sumMetrics = values => {
  const interactions = ["likes", "comments", "shares", "saves"].map(key => values?.[key]).filter(Number.isFinite);
  return { ...values, engagement: interactions.length ? interactions.reduce((a, b) => a + b, 0) : null };
};
function MetricCells({ totals }) { return metrics.map(metric => <td key={metric} title={totals.coverage?.[metric] ? `${totals.coverage[metric].available} of ${totals.coverage[metric].total} deliveries report this metric` : undefined}>{number(totals.values?.[metric])}{totals.coverage?.[metric]?.available > 0 && totals.coverage[metric].available < totals.coverage[metric].total && <sup>*</sup>}</td>); }
function ComparisonChart({ rows, metric }) {
  const max = Math.max(1, ...rows.map(row => Number(row.values?.[metric]) || 0));
  return <div className="bridge-comparison-chart" aria-label={`${labels[metric]} comparison`}>{rows.map((row, index) => <div className="bridge-chart-row" key={row.id}><span title={row.label}>{row.label}</span><div className="bridge-bar-track"><span style={{ width: `${Math.max(0, (row.values?.[metric] || 0) / max * 100)}%`, background: ["#7395ff", "#73c6b5", "#b394ec", "#d5b975"][index % 4] }}/></div><strong>{number(row.values?.[metric])}</strong></div>)}</div>;
}

export default function Analytics({ project, catalog }) {
  const { data, setData, loading, error: loadError, reload } = useProjectResource(project.id, "/analytics", { posts: [], accounts: [], totals: { values: {}, coverage: {} }, publishedCount: 0 });
  const [mode, setMode] = useState("posts"), [accountId, setAccountId] = useState(""), [postId, setPostId] = useState(""), [metric, setMetric] = useState("engagement"), [compare, setCompare] = useState([]), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const account = data.accounts.find(item => item.id === accountId), post = data.posts.find(item => item.id === postId);
  const rows = (mode === "accounts" ? data.accounts.map(item => ({ id: item.id, title: item.label, platform: item.platform, totals: item.totals, count: item.posts.filter(post => post.delivery?.status === "published").length })) : account ? account.posts.filter(item => item.delivery?.status === "published").map(item => ({ ...item, count: 1 })) : data.posts.filter(item => item.deliveries.some(delivery => delivery.status === "published")).map(item => ({ id: item.id, title: item.title || item.caption || "Media post", totals: item.totals, count: item.deliveries.filter(delivery => delivery.status === "published").length }))).sort((a, b) => (b.totals.values[metric] ?? -1) - (a.totals.values[metric] ?? -1));
  const comparisonRows = rows.filter(row => compare.includes(row.id)).map(row => ({ id: row.id, label: row.title, values: row.totals.values }));
  const totals = account && mode === "posts" ? account.totals : data.totals;
  const postRows = post?.deliveries.filter(delivery => delivery.status === "published").map(delivery => ({ ...delivery, values: sumMetrics(delivery.metrics || {}) })).sort((a, b) => (b.values[metric] ?? -1) - (a.values[metric] ?? -1)) || [];
  async function refresh() {
    setBusy(true); setError("");
    try { setData(await api.project(project.id, "/analytics/refresh", { method: "POST", body: { ...(accountId ? { accountId } : {}), ...(mode === "post" && postId ? { postId } : {}) } })); }
    catch (error) { setError(error.message); } finally { setBusy(false); }
  }
  function setScope(nextMode, nextAccount = "", nextPost = "") { setMode(nextMode); setAccountId(nextAccount); setPostId(nextPost); setCompare([]); }
  return <><div className="bridge-intro-row"><p>See what resonates, across posts and accounts.</p><button className="bridge-button secondary" disabled={busy || !data.publishedCount} onClick={refresh}><Icon name="refresh" size={17}/>{busy ? "Refreshing metrics…" : "Refresh metrics"}</button></div><Alert message={error || loadError}/>
    <div className="bridge-stat-grid">{["engagement", "views", "impressions", "clicks"].map(key => <div className="bridge-stat" key={key}><span>{labels[key]}</span><strong>{number(totals.values[key])}</strong><small>{key === "engagement" ? "Reported likes + comments + shares + saves" : "Across published deliveries"}</small></div>)}</div>
    <div className="bridge-library-toolbar"><div className="bridge-filter-tabs"><button className={mode === "posts" ? "active" : ""} onClick={() => setScope("posts")}>Post performance</button><button className={mode === "accounts" ? "active" : ""} onClick={() => setScope("accounts")}>Account performance</button><button className={mode === "post" ? "active" : ""} onClick={() => setScope("post", "", postId || data.posts.find(item => item.deliveries.some(d => d.status === "published"))?.id || "")}>Same post, different accounts</button></div></div>
    <div className="bridge-analytics-filters">{mode === "posts" && <label>View<select value={accountId} onChange={event => { setAccountId(event.target.value); setCompare([]); }}><option value="">All accounts combined</option>{data.accounts.map(item => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label>}{mode === "post" && <label>Post<select value={postId} onChange={event => setPostId(event.target.value)}><option value="">Choose a published post</option>{data.posts.filter(item => item.deliveries.some(delivery => delivery.status === "published")).map(item => <option key={item.id} value={item.id}>{(item.title || item.caption || "Media post").slice(0, 100)}</option>)}</select></label>}<label>Rank by<select value={metric} onChange={event => setMetric(event.target.value)}>{metrics.map(metric => <option value={metric} key={metric}>{labels[metric]}</option>)}</select></label></div>
    <div className="bridge-panel bridge-analytics-main"><div className="bridge-section-label"><div><h2>{mode === "accounts" ? "Compare your accounts" : mode === "post" ? "One post. Every destination." : account ? `Top posts · ${account.label}` : "Top posts across all accounts"}</h2><p className="bridge-small">{mode === "post" ? "Each row shows this post’s performance on one account." : `Sorted by ${labels[metric].toLowerCase()}. Select up to five rows to compare.`}</p></div><Badge>{mode === "post" ? postRows.length : rows.length} {mode === "posts" ? "posts" : "accounts"}</Badge></div>
      {mode === "post" ? postRows.length ? <><ComparisonChart rows={postRows.map(row => ({ id: row.id, label: row.accountName, values: row.values }))} metric={metric}/><div className="bridge-table-scroll"><table className="bridge-table"><thead><tr><th>Account</th>{metrics.map(metric => <th key={metric}>{labels[metric]}</th>)}<th>Last updated</th></tr></thead><tbody>{postRows.map(row => <tr key={row.id}><td><span className="bridge-table-name"><PlatformBadge platform={row.platform} catalog={catalog}/><span>{row.accountName}{row.metricsNote && <small>{row.metricsNote}</small>}{row.metricsError && <small className="bridge-validation-error">{row.metricsError}</small>}</span></span></td><MetricCells totals={{ values: row.values }}/><td>{dateTime(row.metricsUpdatedAt, project.timeZone)}</td></tr>)}<tr className="bridge-total-row"><td>Combined total</td><MetricCells totals={post.totals}/><td/></tr></tbody></table></div></> : <Empty icon="analytics" title="Choose a published post">Compare the same content across its destinations once it has been published.</Empty> : rows.length ? <>{comparisonRows.length > 0 && <div className="bridge-comparison"><div className="bridge-section-label"><strong>Selected {mode === "accounts" ? "accounts" : "posts"}</strong><button className="bridge-text-button" onClick={() => setCompare([])}>Clear comparison</button></div><ComparisonChart rows={comparisonRows} metric={metric}/></div>}<div className="bridge-table-scroll"><table className="bridge-table"><thead><tr><th>Compare</th><th>{mode === "accounts" ? "Account" : "Post"}</th><th>{mode === "accounts" ? "Posts" : "Accounts"}</th>{metrics.map(key => <th key={key}><button className={metric === key ? "active" : ""} onClick={() => setMetric(key)}>{labels[key]}{metric === key ? " ↓" : ""}</button></th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={row.id}><td><input type="checkbox" aria-label={`Compare ${row.title}`} checked={compare.includes(row.id)} disabled={!compare.includes(row.id) && compare.length >= 5} onChange={event => setCompare(current => event.target.checked ? [...current, row.id] : current.filter(id => id !== row.id))}/></td><td><button className="bridge-table-title" onClick={() => mode === "accounts" ? setScope("posts", row.id) : setScope("post", "", row.id)}>{row.platform ? <PlatformBadge platform={row.platform} catalog={catalog}/> : <span className="bridge-rank">{index + 1}</span>}<span>{row.title.slice(0, 90)}</span></button></td><td>{row.count}</td><MetricCells totals={row.totals}/></tr>)}</tbody></table></div></> : <Empty icon="analytics" title={loading ? "Loading analytics…" : "Your results start with a post"}>Once your content is published, you’ll be able to compare its performance here.</Empty>}
    </div>
    <div className="bridge-analytics-notes"><p>{data.engagementDefinition || "Engagement = likes + comments + shares + saves, where reported. Views are separate."}</p><p>— means unavailable or not yet reported. * marks a partial total. Reporting availability and timing vary by platform; refreshes may take a moment. These totals do not deduplicate people across accounts.</p></div>
  </>;
}
