import { useState } from "react";
import { api } from "./BridgeApi.js";
import { Icon } from "./Icons.jsx";
import { Alert, Badge, Check, dateTime, Empty, Field, MediaThumb, useProjectResource } from "./ui.jsx";

export default function ClippingStudio({ project, config, onCompose, onChanged }) {
  const { data, error: loadError, loading, reload } = useProjectResource(project.id, "/clips", { jobs: [] }, { interval: 10000 });
  const [form, setForm] = useState({ youtubeUrl: "", numClips: 5, clipLengthSec: 45, subtitleColor: "#FFFFFF", cropMode: "pad", ownsContent: false }), [busy, setBusy] = useState(false), [error, setError] = useState(""), [activeId, setActiveId] = useState(""), [selected, setSelected] = useState([]), [downloading, setDownloading] = useState(false);
  const active = data.jobs.find(job => job.id === activeId) || data.jobs[0];
  const clips = active?.clips || [];
  const chosen = clips.filter(clip => !clip.unavailable && selected.includes(clip.mediaId));
  const set = (key, value) => setForm(current => ({ ...current, [key]: value }));
  async function generate(event) {
    event.preventDefault(); setBusy(true); setError("");
    try { const { job } = await api.project(project.id, "/clips", { method: "POST", body: form }); setActiveId(job.id); setSelected([]); reload(); }
    catch (error) { setError(error.message); } finally { setBusy(false); }
  }
  async function download(all = false) {
    setDownloading(true); setError("");
    try { await api.download(project.id, all ? `/clips/${active.id}/download` : `/media-download?ids=${chosen.map(clip => clip.mediaId).join(",")}`, "bridge-clips.zip"); }
    catch (error) { setError(error.message); } finally { setDownloading(false); }
  }
  function publish(media) { onChanged(); onCompose(media); }
  return <><div className="bridge-intro-row"><p>Turn a long conversation into short clips. Download them, or send them straight to your publishing queue.</p><Badge>Standalone tool</Badge></div><Alert message={error || loadError}/>
    <div className="bridge-studio-layout"><section className="bridge-panel bridge-studio-settings"><div className="bridge-section-label"><strong>Create clips</strong><Icon name="clips" size={20}/></div><form onSubmit={generate}><Field label="YouTube video"><input type="url" required value={form.youtubeUrl} onChange={event => set("youtubeUrl", event.target.value)} placeholder="https://youtube.com/watch?v=…"/></Field><div className="bridge-field-row"><Field label="Number of clips"><input type="number" min={1} max={30} value={form.numClips} onChange={event => set("numClips", Number(event.target.value))}/></Field><Field label="Target length (seconds)"><input type="number" min={10} max={180} value={form.clipLengthSec} onChange={event => set("clipLengthSec", Number(event.target.value))}/></Field></div><Field label="Vertical framing"><select value={form.cropMode} onChange={event => set("cropMode", event.target.value)}><option value="pad">Fit full frame · background padding</option><option value="crop">Fill frame · center crop</option></select></Field><Field label="Subtitle color"><div className="bridge-color-control"><input type="color" value={form.subtitleColor} onChange={event => set("subtitleColor", event.target.value)}/><span>{form.subtitleColor}</span></div></Field><Check checked={form.ownsContent} onChange={event => set("ownsContent", event.target.checked)}>I own this content or have permission to use it.</Check><button className="bridge-button full" disabled={busy || !form.ownsContent || !config.features?.clipping}>{busy ? "Adding job…" : "Generate clips"}<Icon name="arrow" size={17}/></button></form><p className="bridge-small">Video analysis and rendering can take several minutes. You can leave this screen and return later.</p></section>
      <section className="bridge-studio-results"><div className="bridge-panel"><div className="bridge-section-label"><strong>Clipping jobs</strong><button className="bridge-icon-button" onClick={reload} aria-label="Refresh clipping jobs"><Icon name="refresh" size={17}/></button></div>{data.jobs.length > 0 && <select aria-label="Choose clipping job" value={active?.id || ""} onChange={event => { setActiveId(event.target.value); setSelected([]); }}>{data.jobs.map(job => <option key={job.id} value={job.id}>{job.sourceTitle || "YouTube video"} · {dateTime(job.createdAt, project.timeZone)}</option>)}</select>}
        {!active ? <Empty icon="clips" title={loading ? "Loading clipping jobs…" : "Your next great moment is in there"}>Add a video to find, subtitle, and render its best moments.</Empty> : <div className="bridge-job-summary"><div><h3>{active.sourceTitle || "YouTube video"}</h3><span>{active.stage}</span></div><Badge status={active.status}>{active.status === "done" ? `${clips.length} clips ready` : active.status}</Badge>{["queued", "running"].includes(active.status) && <div className="bridge-job-progress" aria-label={active.stage}><span/></div>}{active.error && <Alert message={active.error}/>}</div>}
      </div>
      {clips.length > 0 && <><div className="bridge-selection-bar"><Check checked={clips.filter(clip => !clip.unavailable).length > 0 && chosen.length === clips.filter(clip => !clip.unavailable).length} onChange={event => setSelected(event.target.checked ? clips.filter(clip => !clip.unavailable).map(clip => clip.mediaId) : [])}>Select all</Check><div className="bridge-inline-actions"><button className="bridge-button secondary small" disabled={downloading} onClick={() => download(true)}><Icon name="download" size={15}/> Download all</button>{chosen.length > 0 && <><button className="bridge-button secondary small" disabled={downloading} onClick={() => download(false)}>Download {chosen.length}</button><button className="bridge-button small" onClick={() => publish(chosen.map(clip => clip.media))}>Create {chosen.length} posts</button></>}</div></div><div className="bridge-clip-grid">{clips.map(clip => <article className="bridge-panel bridge-clip-card" key={clip.mediaId}><div className="bridge-clip-heading"><Check disabled={clip.unavailable} checked={selected.includes(clip.mediaId)} onChange={event => setSelected(current => event.target.checked ? [...current, clip.mediaId] : current.filter(id => id !== clip.mediaId))}>Clip {clip.index}</Check><span className="bridge-score">{clip.viralityScore}<small>potential</small></span></div>{clip.media ? <div className="bridge-clip-video"><MediaThumb media={clip.media} playable/></div> : <p>Media has been removed from the library.</p>}<h3>{clip.title}</h3><p className="bridge-clip-hook">{clip.hook}</p><div className="bridge-clip-meta"><span>{clip.durationSec}s</span><span>{Math.floor(clip.startSec / 60)}:{String(Math.floor(clip.startSec % 60)).padStart(2, "0")} in source</span></div><details><summary>Why this moment · transcript</summary><p className="bridge-small">{clip.reason}</p><div className="bridge-transcript">{clip.transcript.map((phrase, index) => <p key={index}><time>{Math.round(phrase.start)}s</time>{phrase.text}</p>)}</div></details>{!clip.unavailable && <div className="bridge-inline-actions"><a className="bridge-button secondary small" href={clip.downloadUrl} download><Icon name="download" size={15}/> Download</a><button className="bridge-button small" onClick={() => publish([clip.media])}>Create post</button></div>}</article>)}</div></>}
      </section>
    </div>
  </>;
}
