export const PLATFORM_USE_CASES = [
  {
    id: "twitch",
    slug: "twitch-publishing",
    name: "Twitch",
    color: "#9146ff",
    comingSoon: true,
    title: "Twitch Chat Publishing — Coming Soon | Meadow",
    description: "Twitch chat publishing is coming to Meadow: scheduled text messages, replies, follow-up threads, and colored announcements. Not video uploads or live broadcasting.",
    headline: "Twitch chat publishing is coming soon",
    intro: "Bring Twitch channel chat into your publishing plan. Meadow’s integration is built for scheduled text messages, replies, follow-up threads, and colored chat announcements. Production activation is still pending.",
    sectionHeading: "Planned tools for your Twitch community",
    sectionBody: "Connect your own channel through Twitch authorization once the integration is available. This integration is for chat—not video uploads or live broadcasting. Chat engagement analytics are not available.",
    useCases: ["Scheduled channel chat messages", "Replies and follow-up chat threads", "Colored community announcements"],
  },
  {
    id: "kick",
    slug: "kick-publishing",
    name: "Kick",
    color: "#238b00",
    comingSoon: true,
    title: "Kick Chat Publishing — Coming Soon | Meadow",
    description: "Kick chat publishing is coming to Meadow: schedule text messages, reply to existing messages, and plan follow-up threads. Not video uploads or live broadcasting.",
    headline: "Kick chat publishing is coming soon",
    intro: "Plan Kick channel chat alongside your other social content. Meadow’s integration is built for scheduled text messages, replies, and follow-up threads. Production activation is still pending.",
    sectionHeading: "Planned tools for your Kick community",
    sectionBody: "Connect your own channel through Kick authorization once the integration is available. This integration is for chat—not video uploads or live broadcasting. Chat engagement analytics are not available.",
    useCases: ["Scheduled channel chat messages", "Replies to existing chat messages", "Follow-up community threads"],
  },
  {
    id: "x",
    slug: "x-publishing",
    name: "X",
    color: "#171717",
    title: "X Publishing & Scheduling | Meadow",
    description: "Plan, schedule, and publish to X with Meadow. Keep X updates alongside your other social channels in one organized workflow.",
    headline: "X publishing, organized in one place",
    intro: "Keep product news, launch announcements, and timely conversations moving. Prepare posts for X, schedule them, and manage publishing alongside your other channels in Meadow.",
    sectionHeading: "Keep timely X updates on track",
    sectionBody: "Bring upcoming posts into a clear publishing rhythm, so your team can plan ahead and still make room for the conversations happening now.",
    useCases: ["Product news and launch announcements", "Time-sensitive campaign updates", "Ongoing audience conversations"],
  },
  {
    id: "instagram",
    slug: "instagram-publishing",
    name: "Instagram",
    color: "#d94686",
    title: "Instagram Publishing & Scheduling | Meadow",
    description: "Plan and schedule Instagram publishing with Meadow. Coordinate Instagram campaigns with the rest of your social calendar.",
    headline: "Instagram publishing, organized in one place",
    intro: "Plan campaign moments, product stories, and brand updates for Instagram. Schedule publishing alongside your other social channels from one shared workspace.",
    sectionHeading: "Give every Instagram campaign a clear plan",
    sectionBody: "Keep campaign timing and upcoming posts visible together, so your Instagram publishing works in step with the rest of your marketing calendar.",
    useCases: ["Campaigns that need consistent timing", "Product and brand moments", "Coordinated cross-channel launches"],
  },
  {
    id: "linkedin",
    slug: "linkedin-publishing",
    name: "LinkedIn",
    color: "#0a66c2",
    title: "LinkedIn Publishing & Scheduling | Meadow",
    description: "Plan, schedule, and publish LinkedIn updates with Meadow. Keep company news and professional content in your shared social workflow.",
    headline: "LinkedIn publishing, organized in one place",
    intro: "Coordinate company news, product announcements, and professional updates. Plan LinkedIn posts in the same workspace you use to manage publishing across your other channels.",
    sectionHeading: "Bring your LinkedIn publishing into the plan",
    sectionBody: "Keep company communications and campaign activity aligned with a shared schedule, then follow publishing status without switching between separate workflows.",
    useCases: ["Company and product announcements", "Employer brand updates", "Professional campaign content"],
  },
  {
    id: "facebook",
    slug: "facebook-publishing",
    name: "Facebook",
    color: "#1877f2",
    title: "Facebook Publishing & Scheduling | Meadow",
    description: "Organize and schedule Facebook publishing with Meadow. Coordinate page updates and campaigns from one social publishing workspace.",
    headline: "Facebook publishing, organized in one place",
    intro: "Plan page announcements, community updates, and campaign posts for Facebook. Schedule them alongside the rest of your social publishing in Meadow.",
    sectionHeading: "Keep Facebook updates connected to your campaigns",
    sectionBody: "Put upcoming page posts on the same publishing schedule as your other channels, making it easier to prepare updates and keep delivery visible.",
    useCases: ["Page announcements", "Community-focused updates", "Seasonal campaigns"],
  },
  {
    id: "tiktok",
    slug: "tiktok-publishing",
    name: "TikTok",
    color: "#111111",
    title: "TikTok Publishing & Scheduling | Meadow",
    description: "Plan and schedule TikTok publishing with Meadow. Coordinate upcoming TikTok posts with your wider social content calendar.",
    headline: "TikTok publishing, organized in one place",
    intro: "Keep upcoming TikTok posts in view as you plan creator, product, and campaign activity. Schedule publishing and coordinate timing with your other social channels.",
    sectionHeading: "Make TikTok part of your publishing rhythm",
    sectionBody: "Connect your TikTok schedule to the rest of your content plan, so launches and campaign moments stay coordinated across channels.",
    useCases: ["Video release calendars", "Creator and product campaigns", "Time-sensitive launches"],
  },
  {
    id: "youtube",
    slug: "youtube-publishing",
    name: "YouTube",
    color: "#ff0033",
    title: "YouTube Publishing & Scheduling | Meadow",
    description: "Organize YouTube publishing with Meadow. Plan video releases and coordinate them with your other social channels.",
    headline: "YouTube publishing, organized in one place",
    intro: "Plan upcoming video releases, product demos, and channel announcements. Keep YouTube publishing aligned with the campaigns and schedules you manage in Meadow.",
    sectionHeading: "Coordinate video releases with the full campaign",
    sectionBody: "Bring YouTube into your broader publishing calendar, then keep an eye on delivery and available post performance from one workspace.",
    useCases: ["Video release schedules", "Product demos and announcements", "Coordinated campaign launches"],
  },
  {
    id: "telegram",
    slug: "telegram-publishing",
    name: "Telegram",
    color: "#229ed9",
    title: "Telegram Publishing & Scheduling | Meadow",
    description: "Schedule and publish Telegram channel and group updates with Meadow. Coordinate text, photos, videos, albums, and documents with your other social channels.",
    headline: "Telegram publishing, organized in one place",
    intro: "Bring your Telegram channels and groups into the same publishing workflow as your other social accounts. Prepare text, photos, videos, albums, and documents, then publish now or schedule them for later.",
    sectionHeading: "Keep your Telegram community in the loop",
    sectionBody: "Connect through the Meadow bot: add it to your group, or make it a channel administrator with permission to post messages. Coordinate announcements and follow delivery status in Meadow. Telegram post-performance metrics are not available through the Bot API.",
    useCases: ["Channel announcements and product launches", "Scheduled community updates for groups", "Photo albums, videos, and document releases"],
  },
  {
    id: "bluesky",
    slug: "bluesky-publishing",
    name: "Bluesky",
    color: "#168aff",
    title: "Bluesky Publishing & Scheduling | Meadow",
    description: "Plan and schedule Bluesky publishing with Meadow. Keep community updates and announcements in your shared social workflow.",
    headline: "Bluesky publishing, organized in one place",
    intro: "Organize community notes, product updates, and ongoing conversations for Bluesky. Schedule posts in the same workspace as your other social channels.",
    sectionHeading: "Keep your Bluesky presence moving",
    sectionBody: "Plan upcoming updates without losing sight of what is happening across your wider publishing calendar, and follow each post through delivery.",
    useCases: ["Product and community updates", "Event announcements", "Ongoing conversations"],
  },
  {
    id: "threads",
    slug: "threads-publishing",
    name: "Threads",
    color: "#111111",
    title: "Threads Publishing & Scheduling | Meadow",
    description: "Organize Threads publishing with Meadow. Plan conversation-led updates alongside your other social channels.",
    headline: "Threads publishing, organized in one place",
    intro: "Plan conversation-led updates, campaign messages, and company news for Threads. Keep your schedule connected to the rest of your social publishing.",
    sectionHeading: "Keep Threads connected to your content plan",
    sectionBody: "Prepare upcoming posts and coordinate their timing with launches and campaigns on your other channels, all from one shared workflow.",
    useCases: ["Conversation-led campaigns", "Product and company updates", "Community announcements"],
  },
  {
    id: "pinterest",
    slug: "pinterest-publishing",
    name: "Pinterest",
    color: "#e60023",
    title: "Pinterest Publishing & Scheduling | Meadow",
    description: "Plan and schedule Pinterest publishing with Meadow. Keep visual campaigns organized with your wider social calendar.",
    headline: "Pinterest publishing, organized in one place",
    intro: "Plan inspiration-led campaigns, product discovery, and seasonal activity for Pinterest. Coordinate publishing with your other social channels in Meadow.",
    sectionHeading: "Plan Pinterest campaigns with the full picture",
    sectionBody: "Keep upcoming publishing connected to your wider visual campaign schedule, so important moments stay coordinated across your channels.",
    useCases: ["Seasonal inspiration campaigns", "Product discovery content", "Coordinated visual launches"],
  },
  {
    id: "google_business",
    slug: "google-business-publishing",
    name: "Google Business",
    color: "#4285f4",
    title: "Google Business Publishing | Meadow",
    description: "Plan and schedule Google Business updates with Meadow. Coordinate local announcements with your wider social publishing.",
    headline: "Google Business publishing, organized in one place",
    intro: "Plan local announcements, business updates, and seasonal promotions for your Google Business Profile. Keep them in step with the rest of your publishing calendar.",
    sectionHeading: "Keep local updates part of the campaign",
    sectionBody: "Coordinate location-focused publishing with your wider marketing schedule, and see the status of your updates alongside other channels.",
    useCases: ["Local updates and announcements", "Service and location news", "Seasonal promotions"],
  },
];

export function getPlatformUseCaseBySlug(slug) {
  return PLATFORM_USE_CASES.find((platform) => platform.slug === slug);
}

export function getPlatformUseCaseById(id) {
  return PLATFORM_USE_CASES.find((platform) => platform.id === id);
}
